# Generated by Django 3.2.16 on 2023-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('a', 'Automatic'), ('m', 'Manuel')], max_length=1, null=True),
        ),
    ]
